openapi: 3.0.3
info:
  title: Demo App - OpenAPI 3.0
  description: |-
    This is example for Demo App.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/
tags:
  - name: client
    description: Everything about your clients
  - name: provider
    description: Everthing about providers
paths:
  /clients:
    post:
      tags:
        - client
      summary: Get all client to the app
      description: Get all clients 
      operationId: createClient
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
          application/xml:
            schema:
              $ref: '#/components/schemas/Client'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '400':
          description: Bad request
    get:
      tags:
        - client
      summary: Find clients from the app
      description: Find clients from the app
      operationId: getClients
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clients'
        '400':
          description: Bad request
  /clients/{id}:
    get:
      tags:
        - client
      summary: Find client by ID
      description: Returns a single pet
      operationId: getClientById
      parameters:
        - name: id
          in: path
          description: ID of client to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Client not found
    patch:
      tags:
        - client
      summary: Update a client
      operationId: updateClientById
      parameters:
        - name: id
          in: path
          description: client id to update
          required: true
          schema:
            type: string
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClient'
      responses:
        '200':
          description: ok
        '400':
          description: client id not found
    delete:
      tags:
        - client
      summary: Deletes a client
      description: delete a client
      operationId: deleteClient
      parameters:
        - name: id
          in: path
          description: client id to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
        '400':
          description: Invalid client value
  /providers:
    get:
      tags:
        - provider
      summary: Find providers from the app
      description: Find providers from the app
      operationId: getProviders
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getProviders'
components:
  schemas:
    Clients:
      type: array
      items:
        properties:
          _id:
            type: string
            example: 6421893ea84d3231d190bb37
          name:
            type: string
            example: Client 1
          email:
            type: string
            example: abc@axy.com
          phoneNumber:
            type: string
            example: '3055550000'
          providers:
            type: array
            items:
              properties: 
                id:
                  type: string
                  example: 6421893ea84d3231d190bb37          
    Client:
      required:
        - name
        - email
      type: object
      properties:
        name:
          type: string
          example: Client 1
        email:
          type: string
          example: abc@axy.com
        phoneNumber:
          type: string
          example: '3055550000'
        providers:
          type: array
          items:
            properties: 
              id:
                type: string
                example: 6421893ea84d3231d190bb37
    UpdateClient:
      required:
        - name
        - email
      type: object
      properties:
        name:
          type: string
          example: Client 1
        email:
          type: string
          example: abc@axy.com
        providers:
          type: array
          items:
            properties: 
              id:
                type: string
                example: 6421893ea84d3231d190bb37
    getProviders:
      type: array
      items:
        properties:
          name:
            type: string
            example: Provider 1
          _id:
            type: string
            example: 6420a4c62591e163f3d47c3f